version: 2.1

parameters:
  docker-image:
    type: string
    default: "cimg/base:2020.01"

commands:
  git-pr:
    description: "handles PR creation"
    steps:
      - checkout
      - run:
          # The `CIRCLE_PR_NUMBER` variable is only available on forked Pull Requests
          command: |
            set -ex
            if [[ -n "${CIRCLE_PULL_REQUEST}" ]]
            then
                FETCH_REFS="${FETCH_REFS}
                +refs/pull/${CIRCLE_PULL_REQUEST##*/}/merge:pr/${CIRCLE_PULL_REQUEST##*/}/merge"
                git fetch -u origin ${FETCH_REFS}
                git checkout "pr/${CIRCLE_PULL_REQUEST##*/}/merge"
                git log -1 --pretty=format:"%h"
            fi
            set +x
jobs:
  dumb-build:
    docker:
      - image: << pipeline.parameters.docker-image >>
    steps:
      - git-pr
      - run:
          name: "FIXIT: Manipulated failure"
          command: exit 1

workflows:
  version: 2
  Rworkflow:
    jobs:
      - dumb-build
